### ISSUE TITLE
Inspect booking failure codes correctness in TGX-connector

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#569] opened 2021-09-08 11:18 UTC
Need to inspect correctness of booking failure codes and at least use a special code for timeout.
This can be done after updating contracts to 2.1.1

**Comment by DFSko** [comment] 2021-09-09 04:37
Duplicate of happy-travel/agent-app-project#566

**Closed** 2021-09-09 04:43 UTC
Labels: backend, travelgate-connector
