### ISSUE TITLE
Change status in the response when receiving error from provider  

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#73] opened 2021-03-18 05:17 UTC
**How to reproduce:**
- try to book 3 rooms in 'Splendid Venice Starhotels Collezione, Venice, Italy' (NetStorming) for 3 adults using Account balance

**AR**: Got an error while booking a hotel at step 3 _(Supplier Netstorming)_
![unknown](https://user-images.githubusercontent.com/38030865/111576569-cea09380-87c1-11eb-8304-7b99bb1af0b8.png)

![unknown-2](https://user-images.githubusercontent.com/38030865/111576823-48388180-87c2-11eb-91c5-c63c7323a98f.png)

However, now this is not reproduced, perhaps it was a temporary issue of supplier?

**ER**: Empty response with 200 status from connector

**Comment by Raibo** [comment] 2021-04-10 09:08
I close the issue. 
If problem appears in the future, then we'll manage it in a new task and while it reproduces.

**Comment by Raibo** [comment] 2021-04-16 09:39
The problem has returned

**Comment by Raibo** [comment] 2021-04-20 08:27
The user experience is now fixed in https://github.com/happy-travel/agent-app-project/issues/139
Now such issue will only appear in logs, users won't see XML on the front end.

However, I wasn't been able to reproduce the issue.
Finding a booking that naturally responds as "not_available" is not easy, but when I substitute evaluation results in a successful response, no bug occurs, the connector returns null as intended.

I also wasn't been able to retrieve the original Netstorming response, that can cause the connector to return an error. Either there are no logs with raw Netstorming responses, or I missed it somewhere.

**Closed by Raibo** 2021-04-20 08:27 UTC
Labels: backend, booking, bug
